--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/benda95280/MyEntities
branches:
- master
projects:
  MyEntities:
    path: ""
    libs:
    - src: CortexPE/Commando/Commando
      version: ^0.3.1
...
