name: PlayerHeadObj
version: 1.3
main: Benda95280\PlayerHeadObj\PlayerHeadObj
api: 3.0.0
author: Benda95280

permissions:
  playerheadObj:
    description: Main permission
    default: op
    children:
      playerheadObj.give:
        default: op
      playerheadObj.spawn:
        default: op
      playerheadObj.attack:
        default: op
